[package]
name = "rust_start"
version = "0.1.0"
authors = ["zd1998 <zacharycameron3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
